### ISSUE TITLE
Attaching the timestamp to each trash, and not to each box

### ISSUE THREAD

**Issue by bertrandlalo** [surfriderfoundationeurope/etl#7]
https://github.com/surfriderfoundationeurope/etl/blob/159be3e9d8fffdf54351cad733f296e48bc28e07/etl/utils/ai.py#L138-L147

See discussion with Charles here: 
you may (and it happens often) have a single detected trash that is found in mutliple consecutive frames (1 trash = several boxes), for instance:
```
{'detected_trash': [
                    {'frame_to_box': {'2': [0.43, 0.44, 0.49, 0.5], '3':[0.42, 0.44, 0.48, 0.5]},
                       'id': 0,
                       'label': 'fragments'}
}
```
I suggest attaching the timestamp to each trash, and not to each box. The timestamp of the trash should then be the average of the timestamps of the frames with boxes detected (in the example above, (timestamp of frame 2 + timestamp of frame 3)/2).

https://github.com/surfriderfoundationeurope/mot/issues/35

**Comment by cl3m3nt** [comment]
Reviewed
